name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        #bn/ script: sudo sh /opt/git/tera-learn/remote-host/tera-learn/gitcommitscriptexecute.sh   
        script: sudo cd /opt/start-stop/ && sudo /usr/local/bin/terraform apply
#testing
